### ISSUE TITLE
Fix sometimes-failing tests before 3.2.0 release

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1993]
#### Issue description

Some of the mlpack tests seem to be failing; we should avoid making a release until we know that the tests won't regularly fail (thus causing bug reports). :)

Here are the ones I've found that seem to be failing:

- [x] (#1998) `RLComponentsTest/SimplePendulumTest`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/440/armadillo_version=armadillo-7.100.3,boost_version=boost_1_49_0,buildmode=release,compiler_version=gcc-9.2.0,label=docker/testReport/junit/mlpackTest.RLComponentsTest._home_jenkins_workspace_docker.mlpack.nightly/build_armadillo_version_armadillo-7/SimplePendulumTest/)
- [x] (#1995) `RandomForestMainTest/RandomForestDiffMinLeafSize`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/440/armadillo_version=armadillo-8.300.3,boost_version=boost_1_49_0,buildmode=release,compiler_version=gcc-9.2.0,label=docker/)
- [x] (#1995) `RandomForestMainTest/RandomForestDiffNumTreeTest`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/440/armadillo_version=armadillo-8.300.3,boost_version=boost_1_70_0,buildmode=debug,compiler_version=gcc-9.2.0,label=docker/)
- [x] (#1999) `RewardClippingTest/RewardClippedAcrobotWithDQN`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/439/armadillo_version=armadillo-7.100.3,boost_version=boost_1_49_0,buildmode=release,compiler_version=llvm-3.5.2-patch,label=docker/)
- [x] (#2002) `LinearSVMTest/LinearSVMLBFGSTwoClasses`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/439/armadillo_version=armadillo-8.300.3,boost_version=boost_1_70_0,buildmode=release,compiler_version=llvm-8.0.1,label=docker/)
- [x] (#2001) `LSHTest/MultiprobeTest`: [link](http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-8.300.3,boost_version=boost_1_49_0,buildmode=debug,compiler_version=llvm-3.5.2-patch,label=docker/lastCompletedBuild/testReport/)
- [x] (#2000) `CFTest/SerializationUserMeanNormalizationTest`: [link](https://travis-ci.org/mlpack/mlpack/jobs/579245635)
- [x] (#2000) `CFTest/SerializationItemMeanNormalizationTest`: [link](https://travis-ci.org/mlpack/mlpack/jobs/579245635)
- [x] (#2000) `CFTest/SerializationCombinedNormalizationTest`: [link](https://travis-ci.org/mlpack/mlpack/jobs/579245635)

Those last three seem to be only on OS X and may be caused by #1989 (though I think that would be a bit strange).

After fixing all these and re-running the nightly and weekly builds, these tests failed:

 - [x] (#2004) `GmmTrainMainTest/GmmTrainTrialsTest`
 - [x] `QLearningTest/DoubleCartPoleWithDQN`
 - [x] (#2007) `KNNMainTest/KNNAllTreeTypesTest`
 - [x] (#2006) `DecisionTreeTest/PerfectTrainingSet`
 
#### Your environment

 * version of mlpack: git master
 * operating system: Linux, OS X, various
 * compiler: g++, clang
 * version of dependencies (Boost/Armadillo): various
 * any other environment information you think is relevant: these are off the build farm, so various configurations produce the failures

#### Steps to reproduce

Reproducing the test for an individual failure *should* be doable like this:

1. Add the following snippet at the top of the test case (right under `BOOST_AUTO_TEST_CASE()`):

```
mlpack::math::RandomSeed(std::time(NULL));
```

Note that if this is one of the tests in `main_tests/`, because those don't allow setting the random seed, use this instead:

```
const size_t seed = std::time(NULL);
mlpack::math::randGen.seed((uint32_t) seed);
srand((unsigned int) seed);
arma::arma_rng::set_seed(seed);
```

2. Recompile the tests.

3. Run many times until you find a failure (maybe it is useful to print the seed too, so you can reproduce it later).  I typically use a loop like this:

```
$ i=0; while(true); do echo $i; i=$(($i + 1)); bin/mlpack_test -t TestSuiteName/TestCaseName 2>&1 | grep 'fatal'; sleep 1; done
```

#### Expected behavior

Hopefully, the only output from that loop above should be the number of the test, with no failures.

#### Actual behavior

For these tests in particular, it's likely that they'll fail more than once in a thousand runs.  If they do, we should adjust them such that they don't fail.

Generally, but not always, this means increasing the tolerance of the tests.  However, the fact that a test sometimes fails doesn't always mean the tolerance is wrong---it can also mean a deeper issue with the code.

**Comment by rcurtin** [comment]
I opened #1995 for the `RandomForestMainTest` failures.  I'll look into the `LSHTest` failure next; I'm not currently looking into anything else (I'll update this issue if that changes).

**Comment by zoq** [comment]
I opened https://github.com/mlpack/mlpack/pull/1998 for the ``RLComponentsTest/SimplePendulumTest``failure. I'll look into the ``RewardClippingTest/RewardClippedAcrobotWithDQN``failure next.

**Comment by zoq** [comment]
I opened https://github.com/mlpack/mlpack/pull/1999 for the ``RewardClippingTest/RewardClippedAcrobotWithDQN`` failure. Will look into the CF serialization issue next, unless someone else likes to.

**Comment by zoq** [comment]
I opened https://github.com/mlpack/mlpack/pull/2000 for the ``CFTest/SerializationUserMeanNormalizationTest, CFTest/SerializationItemMeanNormalizationTest,  CFTest/SerializationCombinedNormalizationTest`` test failures.

**Comment by rcurtin** [comment]
I figured out the LSH test failure in #2001.

**Comment by jeffin143** [comment]
You both are super heroes :) , opened and debugged in a day :-p

**Comment by rcurtin** [comment]
@jeffin143 thanks!  Mostly I am just letting the tests run in the background and then take a look later.  Usually the fixes are already with code I'm familiar with, so it's not too hard. :)

I investigated the last failing linear SVM test and opened a fix in #2002.

**Comment by rcurtin** [comment]
All the fixes so far are merged.  Now I'm going to run the nightly build and the weekly build and see if there are any additional failures. :)

**Comment by rcurtin** [comment]
Here are the four tests that failed in the weekly and nightly builds:

 - `GmmTrainMainTest/GmmTrainTrialsTest`
 - `QLearningTest/DoubleCartPoleWithDQN`
 - `KNNMainTest/KNNAllTreeTypesTest`
 - `DecisionTreeTest/PerfectTrainingSet`

I updated the issue description above to add those.  I'm working on `GmmTrainTrialsTest` now.

**Comment by zoq** [comment]
Will take a look at the `QLearningTest/DoubleCartPoleWithDQN` failure.

**Comment by rcurtin** [comment]
`GmmTrainMainTest/GmmTrainTrialsTest` should be handled in #2004.  I'll look into `KNNAllTreeTypesTest` tomorrow.

**Comment by KimSangYeon-DGU** [comment]
I'll look into `KNNMainTest/KNNAllTreeTypesTest` tomorrow.

**Comment by rcurtin** [comment]
@KimSangYeon-DGU sounds good, I'll look into `DecisionTreeTest/PerfectTrainingSet` then. :+1:

**Comment by KimSangYeon-DGU** [comment]
@rcurtin Oops... thanks!

**Comment by rcurtin** [comment]
#2006 fixes `DecisionTreeTest/PerfectTrainingSet`.

**Comment by rcurtin** [comment]
I'm also working on the `LinearSVMTest` failures.  These turn out to be caused at a lower level in ensmallen, and I opened mlpack/ensmallen#136 to solve it; but I am also working on workarounds for `linear_svm_test.cpp` now.  I think once those are merged in, we should get some clean builds. :)

**Comment by zoq** [comment]
https://github.com/mlpack/mlpack/pull/2014 should fix the ``QLearningTest/DoubleCartPoleWithDQN``failure.

**Comment by rcurtin** [comment]
I'm sure we will encounter more failing tests in the future, but I think that we have addressed a lot of the big ones that users might encounter failures with.  So for the purpose of mlpack 3.2.0, I think we can close this.
