### ISSUE TITLE
Identify commonly failing tests and address them

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#922]
This is a large ticket that many people can collaborate on.

mlpack has very many tests, and many of these tests are probabilistic.  This means that they can randomly fail, even when something isn't actually wrong with the code.  The purpose of this ticket is to identify these tests, open issues to address those failing tests, and fix the tests.  Typically this will involve understanding an algorithm, understanding the test, and adjusting the tolerance.  This is a good way to get your hands dirty with mlpack, so I think this is a good starter ticket for anyone looking to get involved.  I've labeled it all of 'easy', 'moderate', and 'difficult', because depending on the test, it might be easy to solve and it might not.  Identifying failing tests should be an easy task too.

mlpack has a build server that runs a nightly matrix build.  This can be found at

http://masterblaster.mlpack.org/job/mlpack%20-%20nightly%20matrix%20build/

If you click on any of the 'yellow' builds, you can get to the list of failing tests.  You can also look at the Travis build history for mlpack, or run tests locally.  We should identify tests that fail sometimes, and then open tickets to handle those individually.  I will start with a couple here.

- [ ] `RANNTest/RAModelTest`: #734 (difficult)
- [ ] `LARSTest/NoCholeskyTest`: #355 (difficult) -- only on i386
- [x] `GMMTest/GMMTrainEMOneGaussian`
- [x] `VanillaNetworkTest` in `convolutional_network_test.cpp`
- [x] `EmbeddedReberGrammarTest` in `recurrent_network_test.cpp`
- [x] `LocalCoordinateCodingTest`: #943 (difficult) -- only on sparc64

Debugging tests that fail randomly can be done (or finding how often they fail) can be done by setting the random seed at the top of the test in question:

```
math::RandomSeed(std::time(NULL));
```

Then, you can run that individual test in a loop to see how often it fails:

```
while(true); do bin/mlpack_test -t TestSuiteName/TestCaseName; sleep 1; done
```

and this will run the test over and over again, and you can see how often it fails.  That is usually a good first step to start understanding why the test is failing.

These failing tests are important to fix, because users (and new contributors) often get confused by failing Travis builds.  We can close this bug when we've got the list down to 0. :)

If you'd like to contribute to this effort:

 * Comment with the name of a test that seems to be commonly failing (and I'll update the list above).
 * Open a separate issue for a test that is commonly failing (and I'll update the list above).
 * Investigate a test that is commonly failing and submit a PR to fix it.

**Comment by ThyrixYang** [comment]
Hi @rcurtin , I think a test system should get same  result as long as the function worked correctly. I suggest to run these randomize methods using a fixed seed, and we can choose some seeds and run test on these seeds, to ensure a generic test.

**Comment by ThyrixYang** [comment]
Testing the tolerance of a algorithm can give some information to improve stability, and we can provide a appropriate suggestion(default) tolerance to users. So I think it's better to do a determinate test(same data sets and same random seeds), and consider improve stability   separately

**Comment by rcurtin** [comment]
Unfortunately, "as long as the function worked correctly" is not really an easy thing to know, especially with randomized algorithms.  One example would be LSH, which can't really be tested deterministically.  So we cannot take the randomness out of the tests.  Also, testing on a random dataset instead of a specific, hand-chosen dataset has revealed very many bugs to us in the past.  So I would not want to change the strategy that has been successful for us.

Therefore, our coverage is better if we use randomized tests, and we should focus on making the failure probabilities extremely low.

**Comment by ThyrixYang** [comment]
I see.. What about running the test several times until a success? And only if the tests all failed then throw a fatal error. If it fails on 45% tests(as @lozhnikov said in #734), we can run it for 6 times to ensure a error under 0.01%.(very time consuming indeed, but I think it maybe more robust than change tolerance?)
@rcurtin  Thanks for your detailed explanation, learned a lot. :)

**Comment by rcurtin** [comment]
Yes, running many times is sometimes a solution.  That's done for the simulated annealing tests (`sa_test.cpp`).  #734 will be a bit difficult, because the RASearch algorithm is supposed to guarantee an approximation, and it is failing that guarantee---there is probably something wrong with the algorithm itself (or maybe the guarantee does not apply for certain types of trees).  So unfortunately we can't get away with the strategy of running many times for that one.

**Comment by ThyrixYang** [comment]
I have been reading "IMPROVING DUAL-TREE ALGORITHMS" by you today. I found it wonderful to get familiar with mlpack and dual-tree algorithms (I've been using kd-tree to solve problems in contests, and dual-tree is more powerful). I'll spend some time on #734, may have no progress on this issue, just for my interest.

**Comment by abhinavmoudgil95** [comment]
I am just addressing here the tests which I observed failing quite commonly: 

* `krann_search_test.cpp`
* `convolutional_network_test.cpp`
* `recurrent_network_test.cpp`

Anyone can take them up and fix. Correct me if I am wrong somewhere. :)

**Comment by abhinavmoudgil95** [comment]
Here are some more tests which I observed failing quite commonly: 

* `VanillaNetworkTest` in `convolutional_network_test.cpp`
* `EmbeddedReberGrammarTest` in `recurrent_network_test.cpp`

Anyone can take them up and fix. Correct me if I am wrong somewhere. :)

**Comment by pvskand** [comment]
@abhinavmoudgil95 Can you please tell me how to run the tests for `convolutional_network_test.cpp` ?

**Comment by pvskand** [comment]
@abhinavmoudgil95 I did run the two tests for 25 times each, but did not get any error. Since the initial weights are randomly choosen, I don't think that you should have errors very frequently. Can you tell me with how much frequency is the error show and what is the error in case of `convolutional_network_test.cpp`

**Comment by rcurtin** [comment]
I've updated the list of failing tests, thanks.

When you run the tests to see if they are failing, be sure to add `math::RandomSeed(std::time(NULL))` to the top of the test.

**Comment by shikharbhardwaj** [comment]
I have been able to replicate `ConvolutionalNetworkTest/VanillaNetworkTest` with the seed value 1490461915.

For anyone else trying to work on this issue, I wrote a simple shell script that runs the test again and again till it fails, halting at the failing case : 

    #!/usr/bin/zsh

    correct=0
    while [[ $correct == 0 ]]; do
      ./mlpack_test -t ConvolutionalNetworkTest/VanillaNetworkTest;
      correct=$?;
    done

You can open multiple instances in different terminals if you have more threads to work with.

I'll try and fix the problem with the CNN test.

**Comment by amoudgl** [comment]
@rcurtin I think we can checkoff `VanillaNetworkTest` from the list now.

**Comment by rcurtin** [comment]
Done, thanks again for the contribution!

**Comment by amoudgl** [comment]
Thanks Ryan, always happy to contribute! :)

**Comment by gauravk97** [comment]
Hi, I saw that this issue was still open. I wanted to contribute to mlpack and this seemed a good place to start contributing. Is anybody working on it?  If nobody is then maybe I should? :)

**Comment by rcurtin** [comment]
Hi Gaurav, you are more than welcome to contribute to this issue.  Just identify a commonly failing test (some are listed above) and then see if you can either fix an issue in the code that causes it, or adjust the tolerance of the test accordingly if the code is behaving properly.

**Comment by vmg27** [comment]
Hi @rcurtin, I am getting a failed test for adaboost 'WeakLearnerErrorIris' in my local machine.

`fatal error in "WeakLearnerErrorIris": critical check error <= weakLearnerErrorRate failed [0.040000000000000001 > 0.033333333333333333]`

**Comment by wangxindsb** [comment]
Here are some failed tests which I met:

- 'PerceptronSerializationTest' and 'DecisionStumpSerializationTest' in serialization.cpp;

- 'GMMLoadSaveTest' in gmm_test.cpp;

- 'GMMHMMLoadSaveTest' , 'GaussianHMMLoadSaveTest' and 'DiscreteHMMLoadSaveTest' in hmm_test.cpp;

- 'LSHTest' in serialization_test.cpp;

**Comment by rcurtin** [comment]
@wangxindsb: what version of Boost are you using? This might be the same problem that was just fixed with #1257, if you are using Boost 1.58. If that's the case you could update to the latest code and try again and that would likely fix it.

**Comment by rcurtin** [comment]
I really like the look of the matrix build these days:
http://masterblaster.mlpack.org/job/docker%20mlpack%20monthly%20build/

So I think there are no more "commonly" failing tests, and I think we can finally mark this issue as fixed.
